### PR TITLE
Add Notebook, example of source data file to ScienceBase

### PR DESCRIPTION
**Pull request by dwief-usgs**
Related to the project, "Process Source Files into SFR".   Added a notebook that uses python to retrieve an example source data file and then documents and uploads the file into ScienceBase.  The ScienceBase item can then be used to ensure tracibility to the source data for analytical processes and data management efforts within BCB.

### CODE REVIEW

**Comment by aulenbac** [comment]
@MasoncBSU, could you take a quick look, too? Thanks!

**Comment by skybristol** [comment]
I disagree with @aulenbac on this. https://github.com/usgs-bcb/bcb-dm/blob/master/Protected-Areas.ipynb is more about documenting and reporting on the overall state of managing the Protected Areas data, while Daniel's code here is exploring a methodology for doing an aspect of that work in a new way. That's how I see this process playing out. We describe, explore, and provide evidence of the current state. That effort spins up the need for corrective actions and exploration into new ways of doing things. We go off and do that exploratory work individually and together, resulting in new code and documentation feeding back into the repo as collaborative ideas. We decide on a direction, do a little more engineering on the code, execute those actions, and that changes the current state of managing our data assets. We can then come back to the notebook that documents the current state and change an entire section based on the actions taken and the changed state.

**Comment by skybristol** [comment]
Furthermore, as Daniel said, his work is about this project - https://github.com/usgs-bcb/bcb-dm/projects/1. I think the projects are a good way for us to organize a line of inquiry like this and keep things straight in terms of that issue @aulenbac raised about "cohesive organization." We start from the current state notebooks, identify issues to go track down, spin up a project (before or after we do a little exploratory work), put issues and pull requests into the project as the inquiry proceeds, and close out the project when we are satisfied we've tracked it to ground or reached an MVP.

**Comment by dwief-usgs** [comment]
Few thoughts on the current discussion.  I agree with keeping this as a separate notebook, as it is an exploratory example of what we could be doing.  This conversation does make me rethink breaking the process down into two notebooks though (this being the first, and then another separate notebook for processing into GC2).

**Comment by aulenbac** [comment]
Clearly there are lots of opinions and thoughts flying around about the best way to organize and maintain our work to produce and release product. We'll figure it out as we get further along. For now, let us keep moving forward, merge this new Jupyter notebook and learn how we use this repo.

**Pull request merged**
